module.exports = {
  topic: 'heavens',
  cardId: 'heavens',
  approved: true,
  status: 'approved_frozen',
  questionTypes: ['how_many', 'third_heaven', 'firmament', 'sky', 'celestial', 'no_man_ascended', 'bible_only'],
  approvedCatalogChainKey: 'threeHeavens',
  primaryScriptures: [
    'Genesis 1:1',
    'Genesis 1:6-8',
    'Genesis 1:14-17',
    'Deuteronomy 10:14',
    'John 3:13',
    'John 13:33',
    '2 Corinthians 12:2',
  ],
  supportingScriptures: [
    'Matthew 5:5',
    'Matthew 6:9-10',
    'John 7:33-34',
    'John 8:21',
    'John 14:3',
    'Acts 1:9-11',
    'Acts 2:34',
    'Revelation 5:10',
    'Revelation 11:15',
    'Revelation 20:1-6',
    'Revelation 21:1-3',
  ],
  cautionScriptures: [
    {
      reference: '2 Corinthians 5:8',
      note: 'Absent from the body / present with the Lord — do not use alone as proof of immediate heaven-at-death; weigh death/resurrection chain',
    },
  ],
  cautionPassages: [
    '2 Corinthians 12:2 proves the phrase third heaven exists — Paul’s vision; not normative believer destination',
    'John 3:13 — no man hath ascended up to heaven but the Son of Man',
    'John 13:33 — whither I go, ye cannot come (present separation)',
    'Do not teach believers go to the third heaven unless Scripture explicitly proves that exact claim',
    'Distinguish firmament/sky (Gen 1:6-8), celestial heavens (Gen 1:14-17), and Paul’s third heaven',
  ],
  bindingRules: [
    '2 Corinthians 12:2 names third heaven — does NOT by itself prove believers’ final destination is the third heaven',
    'John 3:13 constrains ascension claims: no man hath ascended except the Son of man',
    'If asked whether believers go to third heaven and Scripture does not state it, say: Scripture does not state that directly',
    'Kingdom hope anchors: Matthew 6:10 on earth; Revelation 5:10 reign on earth; Revelation 21:1-3 comes down',
    '2 Corinthians 5:8 is caution/tension only — not standalone afterlife proof',
  ],
  commonMisreadings: [
    'Collapsing sky/firmament, celestial heavens, and Paul’s third heaven into one count without distinction',
    'Using third heaven as believers’ afterlife destination without Scripture proof',
    'Using 2 Corinthians 5:8 alone to prove immediate heaven at death',
    'Ignoring John 3:13 when discussing ascension or heaven destinations',
  ],
  bibleFirstConclusion:
    'Scripture uses heaven/heavens in layered ways; Paul names a third heaven in 2 Corinthians 12:2 as his experience; Scripture emphasizes kingdom on earth and Christ’s return — not a tradition that believers permanently go to the third heaven.',
  historySecondaryNotes: [],
  confidence: 'high',
  conflictRisk: 'medium',
  lastReviewed: '2026-06-07',
};
