module.exports = {
  topic: 'heavens',
  cardId: 'heavens',
  approved: true,
  status: 'approved_frozen',
  questionTypes: ['how_many', 'third_heaven', 'firmament', 'sky', 'celestial', 'no_man_ascended'],
  primaryScriptures: [
    'Genesis 1:1',
    'Genesis 1:6-8',
    'Genesis 1:14-17',
    '2 Corinthians 12:2',
    'John 3:13',
  ],
  supportingScriptures: [
    'Deuteronomy 10:14',
    'Psalm 19:1',
    'Psalm 148:1-4',
    'Matthew 6:9-10',
    'John 7:33-34',
    'John 8:21',
    'John 13:33',
    'John 14:3',
    'Acts 1:9-11',
    'Revelation 5:10',
    'Revelation 11:15',
    'Revelation 21:1-3',
  ],
  cautionPassages: [
    '2 Corinthians 12:2 — Paul caught up to third heaven (vision); not normative believer destination',
    'John 3:13 — no man hath ascended up to heaven but the Son of Man',
    'Do not teach believers go to the third heaven unless Scripture explicitly proves it',
    'Distinguish firmament/sky (Gen 1:6-8), celestial heavens (Gen 1:14-17), and Paul’s third heaven',
  ],
  commonMisreadings: [
    'Collapsing sky/firmament, celestial heavens, and Paul’s third heaven into one count without distinction',
    'Using third heaven as believers’ afterlife destination without Scripture proof',
    'Redirecting heaven questions to traditions study',
    'Ignoring John 3:13 when discussing ascension or heaven destinations',
  ],
  bibleFirstConclusion:
    'Scripture uses heaven/heavens in layered ways; Paul names a third heaven in 2 Corinthians 12:2 as his experience; answer the user’s specific heaven question first without assuming believer relocation to the third heaven.',
  historySecondaryNotes: [],
  confidence: 'high',
  conflictRisk: 'medium',
  lastReviewed: '2026-06-06',
};
