module.exports = {
  topic: 'kingdom',
  cardId: 'kingdom',
  approved: true,
  status: 'approved_frozen',
  questionTypes: [
    'kingdom_on_earth',
    'thy_kingdom_come',
    'new_jerusalem',
    'second_coming',
    'revelation_21',
    'cannot_come_yet',
    'bible_only',
  ],
  approvedCatalogChainKey: 'kingdomComesToEarth',
  primaryScriptures: [
    'Matthew 5:5',
    'Matthew 6:9-10',
    'John 13:33',
    'John 14:3',
    'Acts 1:9-11',
    'Acts 2:34',
    'Revelation 5:10',
    'Revelation 11:15',
    'Revelation 21:1-3',
  ],
  supportingScriptures: [
    'Genesis 1:1',
    'Genesis 1:6-8',
    'Genesis 1:14-17',
    'Deuteronomy 10:14',
    'John 3:13',
    'John 7:33-34',
    'John 8:21',
    '2 Corinthians 12:2',
    'Revelation 20:1-6',
  ],
  cautionScriptures: [
    {
      reference: '2 Corinthians 5:8',
      note: 'Do not use alone as proof of immediate heaven-at-death; kingdom hope is on earth and resurrection',
    },
  ],
  cautionPassages: [
    'Matthew 6:10 — thy kingdom come, thy will be done in earth as it is in heaven',
    'John 13:33 — whither I go, ye cannot come',
    'John 14:3 — I will come again, and receive you unto myself',
    'Revelation 21:1-3 — holy city comes down; tabernacle of God is with men',
    'Revelation 5:10 — reign on the earth',
  ],
  bindingRules: [
    'The prayer says thy kingdom come… in earth (Matthew 6:9-10)',
    'Revelation shows New Jerusalem coming down — God dwells with men on earth',
    'Revelation 5:10 — saints reign on the earth',
    'Jesus said whither I go ye cannot come (John 13:33) — present separation before glorification',
    'Do not teach believers permanently relocate to third heaven as final hope without direct Scripture proof',
    'If Scripture does not directly state a claim, say: Scripture does not state that directly',
  ],
  commonMisreadings: [
    'Treating mansions language as believers’ immediate heaven destination instead of Christ’s return',
    'Skipping Matthew 6:10 on earth when teaching kingdom hope',
    'Teaching New Jerusalem only as away-from-earth without Revelation 21 coming down',
    'Contrasting heaven vs kingdom as popular tradition instead of Scripture line upon line',
  ],
  bibleFirstConclusion:
    'Scripture frames the kingdom prayer as thy kingdom come on earth; Christ comes again; Revelation describes the holy city coming down and reign on earth — not a simple tradition that believers permanently go to the third heaven.',
  historySecondaryNotes: [],
  confidence: 'high',
  conflictRisk: 'medium',
  lastReviewed: '2026-06-07',
};
