/**
 * UNIFIED_ADMIN_COMMAND_CENTER — Part 9: Future Role-Based Access
 * Foundation.
 *
 * NOT a multi-user login system (none exists today, and this batch does
 * not build one). This module only defines the CAPABILITY vocabulary that
 * navigation and actions are tagged with, so that a future role system
 * can filter navigation/actions by capability without any business logic
 * needing to know role names.
 *
 * Today: the single existing Admin token (BIBLE_AUTHORITY_ADMIN_TOKEN /
 * ALPHA_ADMIN_TOKEN / BETA_REVIEW_TOKEN) grants EVERY capability below —
 * current behavior is completely unchanged. `getCurrentActorCapabilities`
 * always returns the full OWNER set while only one credential exists.
 */

const CAPABILITIES = {
  VIEW_EXECUTIVE_OVERVIEW: 'VIEW_EXECUTIVE_OVERVIEW',
  VIEW_USERS_SESSIONS: 'VIEW_USERS_SESSIONS',
  VIEW_SCRIPTURE_KNOWLEDGE: 'VIEW_SCRIPTURE_KNOWLEDGE',
  VIEW_LESSON_ALIGNMENT: 'VIEW_LESSON_ALIGNMENT',
  VIEW_FOUNDER_INTELLIGENCE: 'VIEW_FOUNDER_INTELLIGENCE',
  VIEW_OPERATIONS_HEALTH: 'VIEW_OPERATIONS_HEALTH',
  VIEW_DECISIONS_AUDIT: 'VIEW_DECISIONS_AUDIT',
  VIEW_SECURITY: 'VIEW_SECURITY',
  USE_GLOBAL_SEARCH: 'USE_GLOBAL_SEARCH',
  USE_AI_CHIEF_OF_STAFF: 'USE_AI_CHIEF_OF_STAFF',
  ACT_ON_DECISION_QUEUE: 'ACT_ON_DECISION_QUEUE',
  APPROVE_RECOMMENDATIONS: 'APPROVE_RECOMMENDATIONS',
  MANAGE_LESSON_ALIGNMENT: 'MANAGE_LESSON_ALIGNMENT',
};

// Future roles (documented, not implemented as real logins). Each maps to
// a subset of CAPABILITIES that a future auth layer would grant.
const FUTURE_ROLE_CAPABILITY_MAP = {
  OWNER_CEO: Object.values(CAPABILITIES),
  SCRIPTURE_GOVERNANCE_ADMINISTRATOR: [
    CAPABILITIES.VIEW_EXECUTIVE_OVERVIEW,
    CAPABILITIES.VIEW_SCRIPTURE_KNOWLEDGE,
    CAPABILITIES.VIEW_DECISIONS_AUDIT,
    CAPABILITIES.ACT_ON_DECISION_QUEUE,
    CAPABILITIES.APPROVE_RECOMMENDATIONS,
    CAPABILITIES.USE_GLOBAL_SEARCH,
  ],
  TECHNICAL_ADMINISTRATOR: [
    CAPABILITIES.VIEW_EXECUTIVE_OVERVIEW,
    CAPABILITIES.VIEW_OPERATIONS_HEALTH,
    CAPABILITIES.VIEW_SECURITY,
    CAPABILITIES.USE_GLOBAL_SEARCH,
    CAPABILITIES.USE_AI_CHIEF_OF_STAFF,
  ],
  USER_SUPPORT: [
    CAPABILITIES.VIEW_EXECUTIVE_OVERVIEW,
    CAPABILITIES.VIEW_USERS_SESSIONS,
    CAPABILITIES.USE_GLOBAL_SEARCH,
  ],
  LESSON_REVIEWER: [
    CAPABILITIES.VIEW_LESSON_ALIGNMENT,
    CAPABILITIES.MANAGE_LESSON_ALIGNMENT,
    CAPABILITIES.ACT_ON_DECISION_QUEUE,
  ],
  CONTENT_REVIEWER: [
    CAPABILITIES.VIEW_SCRIPTURE_KNOWLEDGE,
    CAPABILITIES.VIEW_FOUNDER_INTELLIGENCE,
    CAPABILITIES.ACT_ON_DECISION_QUEUE,
    CAPABILITIES.APPROVE_RECOMMENDATIONS,
  ],
  SECURITY_AND_COMPLIANCE: [
    CAPABILITIES.VIEW_SECURITY,
    CAPABILITIES.VIEW_DECISIONS_AUDIT,
    CAPABILITIES.VIEW_OPERATIONS_HEALTH,
  ],
  READ_ONLY_ANALYST: [
    CAPABILITIES.VIEW_EXECUTIVE_OVERVIEW,
    CAPABILITIES.VIEW_USERS_SESSIONS,
    CAPABILITIES.VIEW_SCRIPTURE_KNOWLEDGE,
    CAPABILITIES.VIEW_FOUNDER_INTELLIGENCE,
    CAPABILITIES.VIEW_OPERATIONS_HEALTH,
    CAPABILITIES.USE_GLOBAL_SEARCH,
  ],
};

/**
 * Today there is exactly one credential and it grants every capability —
 * this function is the single seam a future multi-role auth layer would
 * change (look up the actor's real role -> FUTURE_ROLE_CAPABILITY_MAP)
 * without any navigation/action code elsewhere needing to change.
 */
function getCurrentActorCapabilities(/* req */) {
  return Object.values(CAPABILITIES);
}

module.exports = { CAPABILITIES, FUTURE_ROLE_CAPABILITY_MAP, getCurrentActorCapabilities };
