/**
 * Approved Support Graph — encodes frozen evidence-card relationships for claim verification.
 * Does not speak to users; feeds Support Relationship Engine only.
 */

const { buildApprovedCatalogEvidence, collectApprovedReferences } = require('./approvedCatalogEvidence');
const { refMatchesPattern, refMatchesApproved } = require('./scriptureReferenceNormalizer');

const SUPPORT_CLASS_BY_TYPE = {
  directly_affirms: 'A',
  indirectly_supports: 'B',
  cautions_against: 'C',
  limits_claim: 'C',
  scripture_silent: 'C',
  contradicts: 'D',
};

const RELATIONSHIP_BY_TYPE = {
  directly_affirms: 'direct',
  indirectly_supports: 'chain',
  cautions_against: 'limits',
  limits_claim: 'limits',
  scripture_silent: 'unverified',
  contradicts: 'contradicted',
};

/**
 * Frozen support edges transcribed from approved cards, bindingRules, cautionPassages, catalogs.
 * No new doctrine — only existing approved evidence.
 */
const APPROVED_SUPPORT_EDGES = [
  // --- dietaryLaw ---
  {
    id: 'lev11_swine_unclean',
    topic: 'dietary_law',
    cardId: 'dietaryLaw',
    claimPatterns: [
      /\b(swine|pork)\b.{0,30}\b(unclean|not clean)\b/i,
      /\bunclean\b.{0,30}\b(swine|pork)\b/i,
      /\blists?\b.{0,20}\b(swine|pork)\b/i,
    ],
    refPatterns: [/\b(leviticus\s*11|deuteronomy\s*14)\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Leviticus 11', 'Deuteronomy 14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'dietaryLaw.card bibleFirstConclusion',
    approved: true,
  },
  {
    id: 'acts10_28_people_not_food',
    topic: 'dietary_law',
    cardId: 'dietaryLaw',
    claimPatterns: [
      /\bvision\b.{0,50}\b(people|gentiles|man|men)\b/i,
      /\bnot food\b/i,
      /\babout\b.{0,30}\b(people|gentiles)\b/i,
      /\bcommon or unclean\b/i,
      /\bacceptance of gentiles\b/i,
      /\bdoesn'?t overturn\b.{0,30}\b(clean|unclean|food)\b/i,
      /\bnot\b.{0,20}\b(call|called)\b.{0,20}\bunclean\b/i,
      /\bpeople\b.{0,30}\bnot\b.{0,20}\bunclean\b/i,
      /\brelates to people\b/i,
      /\bnot\b.{0,20}\b(animals|food)\b/i,
      /\binstruction\b.{0,30}\bpeople\b/i,
    ],
    refPatterns: [/\bacts\s*10:28\b/i, /\bacts\s*10\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Acts 10:28'],
    relationship: 'direct',
    confidence: 'high',
    source: 'dietaryLaw.card cautionPassages',
    approved: true,
  },
  {
    id: 'isa66_unclean_distinction',
    topic: 'dietary_law',
    cardId: 'dietaryLaw',
    claimPatterns: [
      /\b(unclean|abominable)\b.{0,30}\b(animals?|things?|creatures?)\b/i,
      /\bdistinction\b.{0,30}\b(unclean|clean)\b/i,
      /\bmaintain(ed|s)?\b.{0,30}\b(distinction|unclean)\b/i,
      /\bdistinction\b.{0,30}\bmaintain(ed|s)?\b/i,
      /\bthroughout scripture\b/i,
      /\bprophetic\b.{0,30}\b(unclean|abominable)\b/i,
    ],
    refPatterns: [/\bisaiah\s*66:17\b/i, /\bisaiah\s*66\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Isaiah 66:17'],
    relationship: 'direct',
    confidence: 'high',
    source: 'dietaryLaw.card supportingScriptures',
    approved: true,
  },
  {
    id: 'acts11_gentile_clarification',
    topic: 'dietary_law',
    cardId: 'dietaryLaw',
    claimPatterns: [
      /\b(gentiles?|people)\b.{0,40}\bnot\b.{0,20}\bfood\b/i,
      /\bvision\b.{0,40}\b(gentiles?|people)\b/i,
      /\bfood laws?\b/i,
      /\bacts\s*11\b/i,
      /\bexplains\b.{0,30}\bvision\b/i,
      /\bdoes not\b.{0,30}\b(overturn|change|clean|declare)\b/i,
      /\bconfirm(s|ing)?\b.{0,30}\b(vision|meaning)\b/i,
      /\bexplains\b.{0,40}\bvision'?s?\s+meaning\b/i,
      /\bnot\b.{0,20}\babout\b.{0,20}\bfood\b/i,
      /\bpeter\b.{0,40}\b(explanation|clarif)\b/i,
      /\bvision'?s?\s+meaning\b/i,
      /\bearly church\b/i,
    ],
    refPatterns: [/\bacts\s*11\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Acts 11:1-18'],
    relationship: 'direct',
    confidence: 'high',
    source: 'dietaryLaw.card bibleFirstConclusion',
    approved: true,
  },
  {
    id: 'acts10_14_never_eaten_unclean',
    topic: 'dietary_law',
    cardId: 'dietaryLaw',
    claimPatterns: [
      /\bnever\b.{0,30}\b(eaten|eat)\b.{0,30}\b(common|unclean)\b/i,
      /\bnot\b.{0,20}\b(eaten|eat)\b.{0,20}\b(unclean|common)\b/i,
    ],
    refPatterns: [/\bacts\s*10:14\b/i, /\bacts\s*10\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Acts 10:14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'dietaryLaw.card supportingScriptures',
    approved: true,
  },
  {
    id: 'acts10_not_pork_clean',
    topic: 'dietary_law',
    cardId: 'dietaryLaw',
    claimPatterns: [
      /\b(makes?|made|declares?)\b.{0,30}\b(all foods|pork|unclean).{0,20}\bclean\b/i,
      /\b(yes|indeed)\b.{0,20}\b(pork|unclean).{0,20}\b(clean|permitted)\b/i,
      /\bcan\s+(now\s+)?eat\s+pork\b/i,
      /\bacts\s*10\b.{0,60}\b(clean|permitted)\b/i,
    ],
    refPatterns: [/\bacts\s*10\b/i],
    supportType: 'contradicts',
    scriptures: ['Acts 10'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'dietaryLaw.card cautionPassages',
    approved: true,
  },
  {
    id: 'lev11_not_pork_clean',
    topic: 'dietary_law',
    cardId: 'dietaryLaw',
    claimPatterns: [
      /\b(pork|swine)\b.{0,30}\b(clean|permitted|allowed)\b/i,
      /\b(yes|can)\b.{0,20}\b(eat\s+)?pork\b/i,
      /\bpork is clean\b/i,
    ],
    refPatterns: [/\b(leviticus\s*11|deuteronomy\s*14)\b/i],
    supportType: 'contradicts',
    scriptures: ['Leviticus 11', 'Deuteronomy 14'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'dietaryLaw.card bibleFirstConclusion',
    approved: true,
  },
  // --- heavens ---
  {
    id: '2cor12_2_names_third_heaven',
    topic: 'heavens',
    cardId: 'heavens',
    claimPatterns: [
      /\bpaul\b.{0,40}\b(names|mentions|caught up|saw)\b.{0,40}\bthird heaven\b/i,
      /\bthird heaven\b.{0,40}\b(named|mentioned|exists|caught up)\b/i,
      /\bapostle paul\b.{0,40}\bthird heaven\b/i,
    ],
    refPatterns: [/\b2\s*cor(?:inthians)?\s*12:2\b/i, /\b2\s*cor(?:inthians)?\s*12\b/i],
    supportType: 'directly_affirms',
    scriptures: ['2 Corinthians 12:2-4'],
    relationship: 'direct',
    confidence: 'high',
    source: 'heavens.card bindingRules',
    approved: true,
  },
  {
    id: '2cor12_2_not_destination',
    topic: 'heavens',
    cardId: 'heavens',
    claimPatterns: [
      /\bbelievers?\b.{0,40}\b(go|ascend|enter)\b.{0,30}\b(third heaven|heaven)\b/i,
      /\b(third heaven|destination|eternal home)\b.{0,40}\b(proves?|shows?|means?)\b/i,
      /\bproves?\b.{0,50}\b(third heaven|eternal home|believers?['']?\s+(destination|final))\b/i,
      /\bfinal destination\b.{0,30}\bthird heaven\b/i,
    ],
    refPatterns: [/\b2\s*cor(?:inthians)?\s*12:2\b/i, /\b2\s*cor(?:inthians)?\s*12\b/i],
    supportType: 'limits_claim',
    scriptures: ['2 Corinthians 12:2-4'],
    relationship: 'limits',
    confidence: 'high',
    source: 'heavens.card bindingRules',
    approved: true,
    classificationOverride: 'D',
  },
  {
    id: 'john3_13_no_ascension',
    topic: 'heavens',
    cardId: 'heavens',
    claimPatterns: [
      /\bno man\b.{0,40}\bascended\b/i,
      /\bno one\b.{0,40}\bascended\b/i,
      /\bexcept\b.{0,20}\bson of man\b/i,
      /\bonly christ\b.{0,30}\bascended\b/i,
      /\blimits?\b.{0,30}\bascension\b/i,
    ],
    refPatterns: [/\bjohn\s*3:13\b/i, /\bjohn\s*3\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 3:13'],
    relationship: 'direct',
    confidence: 'high',
    source: 'heavens.card bindingRules',
    approved: true,
  },
  {
    id: 'john3_13_not_believer_ascension',
    topic: 'heavens',
    cardId: 'heavens',
    claimPatterns: [
      /\bbelievers?\s+have\s+ascended\b/i,
      /\b(men|people)\s+have\s+ascended\b/i,
    ],
    refPatterns: [/\bjohn\s*3:13\b/i],
    supportType: 'contradicts',
    scriptures: ['John 3:13'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'heavens.card bindingRules',
    approved: true,
  },
  {
    id: '2cor5_8_not_immediate_heaven',
    topic: 'heavens',
    cardId: 'heavens',
    claimPatterns: [
      /\b(heaven at death|immediate heaven|go to heaven when we die)\b/i,
      /\b(proves?|means?|shows?)\b.{0,30}\b(heaven at death|immediate)\b/i,
    ],
    refPatterns: [/\b2\s*cor(?:inthians)?\s*5:8\b/i],
    supportType: 'contradicts',
    scriptures: ['2 Corinthians 5:8'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'heavens.card cautionScriptures',
    approved: true,
  },
  {
    id: '2cor5_8_absent_with_lord_context',
    topic: 'heavens',
    cardId: 'heavens',
    claimPatterns: [
      /\babsent from the body\b/i,
      /\bwith the lord\b/i,
      /\bconfidence\b.{0,30}\b(lord|present)\b/i,
      /\bexpresses\b.{0,30}\b(hope|confidence)\b/i,
      /\bunderstood with caution\b/i,
      /\bshould be understood\b/i,
    ],
    refPatterns: [/\b2\s*cor(?:inthians)?\s*5:8\b/i],
    supportType: 'indirectly_supports',
    scriptures: ['2 Corinthians 5:8'],
    relationship: 'chain',
    confidence: 'medium',
    source: 'heavens.card cautionScriptures',
    approved: true,
  },
  // --- kingdom ---
  {
    id: 'matt6_10_kingdom_on_earth',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\bkingdom\b.{0,40}\b(on earth|in earth|come)\b/i,
      /\bthy kingdom come\b/i,
      /\bwill be done\b.{0,20}\b(in earth|on earth)\b/i,
      /\bkingdom\b.{0,30}\b(grounding|hope|focus)\b.{0,20}\bearth\b/i,
      /\bfuture reality\b.{0,40}\b(on earth|in earth)\b/i,
    ],
    refPatterns: [/\bmatthew\s*6:9-10\b/i, /\bmatthew\s*6:10\b/i, /\bmatthew\s*6\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Matthew 6:9-10'],
    relationship: 'direct',
    confidence: 'high',
    source: 'kingdom.card bindingRules',
    approved: true,
  },
  {
    id: 'matt6_10_not_kingdom_in_heaven',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\bkingdom\b.{0,50}\b(in heaven|only in heaven)\b.{0,40}\b(believers?|go|after death)\b/i,
      /\bbelievers?\b.{0,40}\bgo\b.{0,30}\bheaven\b.{0,30}\bkingdom\b/i,
    ],
    refPatterns: [/\bmatthew\s*6:9-10\b/i, /\bmatthew\s*6:10\b/i],
    supportType: 'contradicts',
    scriptures: ['Matthew 6:9-10'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'kingdom.card bindingRules',
    approved: true,
  },
  {
    id: 'john14_3_come_again',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\bcome again\b/i,
      /\breceive\b.{0,30}\b(you|followers|believers|unto myself)\b/i,
      /\breturn\b.{0,30}\b(bring|receive)\b/i,
      /\bpromises?\b.{0,30}\bchrist'?s?\b.{0,30}\breturn\b/i,
    ],
    refPatterns: [/\bjohn\s*14:3\b/i, /\bjohn\s*14\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 14:3'],
    relationship: 'direct',
    confidence: 'high',
    source: 'kingdom.card cautionPassages',
    approved: true,
  },
  {
    id: 'john13_33_cannot_come',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\b(cannot|can not)\s+come\b/i,
      /\bwhither i go\b.{0,40}\b(cannot|can not)\b/i,
      /\bye cannot come\b/i,
      /\bseparation\b.{0,30}\b(before|return|christ)\b/i,
      /\blimits?\b.{0,30}\b(heaven|destination|traditional)\b/i,
      /\bdirectly states\b/i,
      /\bwhere i go\b/i,
      /\btelling\b.{0,30}\b(disciples|followers)\b/i,
    ],
    refPatterns: [/\bjohn\s*13:33\b/i, /\bjohn\s*13\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 13:33'],
    relationship: 'direct',
    confidence: 'high',
    source: 'kingdom.card bindingRules',
    approved: true,
  },
  {
    id: 'john13_33_not_permanent_heaven',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\b(join|be with)\s+jesus\b.{0,50}\bheaven\b/i,
      /\bpermanently\b.{0,40}\b(heaven|away from earth)\b/i,
      /\bbelievers?\b.{0,40}\bjoin\b.{0,40}\bjesus\b.{0,40}\bheaven\b/i,
    ],
    refPatterns: [/\bjohn\s*13:33\b/i],
    supportType: 'contradicts',
    scriptures: ['John 13:33'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'kingdom.card bindingRules',
    approved: true,
  },
  {
    id: 'rev21_comes_down',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\bnew heaven\b/i,
      /\bnew earth\b/i,
      /\b(holy city|new jerusalem)\b/i,
      /\b(dwell|tabernacle)\b.{0,30}\b(with men|with man|with people)\b/i,
      /\bcomes?\s+down\b/i,
      /\bgod\b.{0,30}\bdwells?\b/i,
    ],
    refPatterns: [/\brevelation\s*21:1-3\b/i, /\brevelation\s*21\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Revelation 21:1-3'],
    relationship: 'direct',
    confidence: 'high',
    source: 'kingdom.card bindingRules',
    approved: true,
  },
  {
    id: 'rev5_10_reign_earth',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\breign\b.{0,30}\b(on earth|earth)\b/i,
      /\bsaints?\b.{0,30}\breign\b/i,
    ],
    refPatterns: [/\brevelation\s*5:10\b/i, /\brevelation\s*5\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Revelation 5:10'],
    relationship: 'direct',
    confidence: 'high',
    source: 'kingdom.card bindingRules',
    approved: true,
  },
  {
    id: 'third_heaven_destination_denial',
    topic: 'heavens',
    cardId: 'heavens',
    claimPatterns: [
      /\bbelievers?\s+go\s+to\s+(the\s+)?third\s+heaven\b/i,
      /\b(third heaven|3rd heaven)\b.{0,50}\b(final destination|where believers|we go when we die)\b/i,
    ],
    refPatterns: [/\b2\s*cor(?:inthians)?\s*12\b/i, /\bthird heaven\b/i],
    supportType: 'contradicts',
    scriptures: ['2 Corinthians 12:2'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'heavens.card bindingRules',
    approved: true,
  },
  // --- sabbath (from sabbath.card primaryScriptures, supportingScriptures, bibleFirstConclusion) ---
  {
    id: 'gen2_sabbath_rest_established',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\b(seventh day|sabbath)\b.{0,40}\b(rest|rested|resting|blessed|sanctified)\b/i,
      /\brest(ing|ed)?\b.{0,40}\b(seventh day|creation|sabbath)\b/i,
      /\bestablished\b.{0,40}\b(pattern|sabbath|seventh|creation)\b/i,
      /\bgod rest(ed|ing)?\b/i,
      /\bceas(e|ing)\b.{0,20}\bfrom\b.{0,20}\bwork\b/i,
      /\b(at )?creation\b.{0,30}\b(sabbath|seventh)\b/i,
    ],
    refPatterns: [/\bgenesis\s*2:2-3\b/i, /\bgenesis\s*2\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Genesis 2:2-3'],
    relationship: 'direct',
    confidence: 'high',
    source: 'sabbath.card primaryScriptures + bibleFirstConclusion',
    approved: true,
  },
  {
    id: 'ex20_remember_sabbath',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\bremember(ing)?\b.{0,30}\bsabbath\b/i,
      /\bkeep(ing)?\b.{0,20}\b(holy|sabbath)\b/i,
      /\bceas(e|ing)\b.{0,20}\bwork\b/i,
      /\bcommand(ment|ing)?\b.{0,30}\b(sabbath|seventh|rest)\b/i,
      /\bordinary work\b/i,
      /\bfourth commandment\b/i,
      /\bten commandments\b/i,
      /\bprescribes?\b.{0,20}\b(seventh day|sabbath)\b/i,
      /\bestablishes?\b.{0,30}\b(seventh day|sabbath)\b/i,
      /\bfoundation\b.{0,30}\b(worship|scripture|practice)\b/i,
      /\bexplicitly\b.{0,30}\b(seventh day|sabbath)\b/i,
    ],
    refPatterns: [/\bexodus\s*20:8-11\b/i, /\bexodus\s*20\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Exodus 20:8-11'],
    relationship: 'direct',
    confidence: 'high',
    source: 'sabbath.card primaryScriptures',
    approved: true,
  },
  {
    id: 'isa58_delight_in_sabbath',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\bdelight(ing|ed)?\b.{0,40}\b(sabbath|lord)\b/i,
      /\b(sabbath|lord)\b.{0,40}\bdelight(ing|ed)?\b/i,
      /\bpleasure\b/i,
      /\bdoing good\b/i,
      /\bshowing mercy\b/i,
      /\bmercy\b/i,
      /\bturn(ing)?\b.{0,30}\b(pleasure|away|own ways)\b/i,
      /\bown (ways|business|pleasure)\b/i,
      /\bpersonal business\b/i,
      /\brefrain(ing)?\b.{0,30}\b(business|ways|pleasure)\b/i,
      /\bholy day\b/i,
      /\bhonor(ing)?\b.{0,30}\b(sabbath|lord|his day)\b/i,
      /\bceas(e|ing)\b.{0,30}\b(business|work)\b/i,
      /\blasting sign\b/i,
      /\bblessing\b.{0,20}\bfrom god\b/i,
      /\bsign\b.{0,30}\b(sabbath|covenant)\b/i,
      /\b(covenant|worship)\b.{0,30}\b(sabbath|rest)\b/i,
      /\bremains\b.{0,30}\b(sign|sabbath)\b/i,
    ],
    refPatterns: [/\bisaiah\s*58:13-14\b/i, /\bisaiah\s*58\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Isaiah 58:13-14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'sabbath.card supportingScriptures',
    approved: true,
  },
  {
    id: 'luke4_jesus_sabbath_custom',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\bjesus\b.{0,40}\b(sabbath|synagogue|worship|attend)\b/i,
      /\bhabit\b.{0,30}\b(worship|sabbath)\b/i,
      /\battend(ing|ed)?\b.{0,30}\b(sabbath|synagogue)\b/i,
      /\bregularly attended\b/i,
      /\bexample\b.{0,30}\b(sabbath|synagogue)\b/i,
      /\bshowed example\b/i,
    ],
    refPatterns: [/\bluke\s*4:16\b/i, /\bluke\s*4\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Luke 4:16'],
    relationship: 'direct',
    confidence: 'high',
    source: 'sabbath.card supportingScriptures',
    approved: true,
  },
  {
    id: 'acts17_sabbath_teaching',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\b(believers?|christians?|paul|apostles?|early believers|early christians)\b.{0,50}\b(sabbath|synagogue)\b/i,
      /\bgather(ing|ed)?\b.{0,40}\b(sabbath|teaching|hear|word)\b/i,
      /\bmet\b.{0,30}\b(sabbath|synagogue)\b/i,
      /\bmeeting\b.{0,30}\b(sabbath|teaching)\b/i,
      /\breasoned\b.{0,30}\bsabbath\b/i,
      /\bcontinued\b.{0,30}\b(sabbath|meeting)\b/i,
      /\bobserved\b.{0,20}\bthe sabbath\b/i,
      /\bstill\b.{0,30}\b(sabbath|observed)\b/i,
      /\b(christians?|believers?)\b.{0,50}\bsabbath\b/i,
    ],
    refPatterns: [/\bacts\s*17:2\b/i, /\bacts\s*17\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Acts 17:2'],
    relationship: 'direct',
    confidence: 'high',
    source: 'sabbath.card supportingScriptures',
    approved: true,
  },
  {
    id: 'heb4_sabbath_rest_remains',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\bsabbath rest\b/i,
      /\brest\b.{0,40}\b(remain|remains|remaining)\b/i,
      /\bremains?\b.{0,40}\b(god'?s people|people of god)\b/i,
      /\bspeaks of a sabbath rest\b/i,
      /\brest for god'?s people\b/i,
      /\blasting sign\b.{0,30}\brest\b/i,
    ],
    refPatterns: [/\bhebrews\s*4:9\b/i, /\bhebrews\s*4\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Hebrews 4:9'],
    relationship: 'direct',
    confidence: 'high',
    source: 'sabbath.card supportingScriptures',
    approved: true,
  },
  {
    id: 'ex31_sabbath_sign_covenant_batch2m',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\b(sign|covenant)\b.{0,40}\b(sabbath|seventh)\b/i,
      /\b(sabbath|seventh day)\b.{0,40}\b(sign|covenant|perpetual)\b/i,
      /\bperpetual\b.{0,30}\b(covenant|sign)\b/i,
      /\bmy sabbaths\b/i,
      /\bset apart\b.{0,30}\bsabbath\b/i,
    ],
    refPatterns: [
      /exodus\s*31:13/i,
      /exodus\s*31\b/i,
    ],
    supportType: 'directly_affirms',
    scriptures: ['Exodus 31:13', 'Exodus 20:8-11', 'Genesis 2:2-3', 'Revelation 14:12'],
    relationship: 'chain',
    confidence: 'high',
    source: '2M second batch rec_0003 covenant sign G2R witness',
    approved: true,
  },
  {
    id: 'mat12_sabbath_do_good_batch3p',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\b(do good|lawful)\b.{0,40}\b(sabbath|sabbath day)\b/i,
      /\b(sabbath|sabbath day)\b.{0,40}\b(do good|lawful)\b/i,
      /\bkeep\b.{0,30}\b(holy|sabbath)\b/i,
      /\bholy\b.{0,30}\bsabbath\b/i,
    ],
    refPatterns: [
      /matthew\s*12:11/i,
      /matthew\s*12\b/i,
    ],
    supportType: 'directly_affirms',
    scriptures: ['Matthew 12:11-12', 'Exodus 20:8-11', 'Genesis 2:2-3'],
    relationship: 'direct',
    confidence: 'high',
    source: '2P Sabbath Pack exp_0011 holy Sabbath command',
    approved: true,
  },
    {
    id: 'heb4_seventh_day_remains_batch3p',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\bhebrews\s*4\b.{0,50}\b(abolish|cancel|no longer|not need)\b.{0,30}\b(seventh|sabbath)\b/i,
      /\b(no longer|not need)\b.{0,40}\b(seventh day|sabbath)\b/i,
      /\bseventh day\b.{0,40}\b(abolish|cancel|done away)\b/i,
      /\bsabbath rest\b.{0,40}\b(remains|remain)\b/i,
    ],
    refPatterns: [
      /hebrews\s*4:9/i,
      /hebrews\s*4\b/i,
    ],
    supportType: 'directly_affirms',
    scriptures: ['Hebrews 4:9', 'Genesis 2:2-3', 'Exodus 20:8-11', 'Revelation 14:12'],
    relationship: 'chain',
    confidence: 'high',
    source: '2P Sabbath Pack exp_0023 Hebrews 4 seventh-day remains',
    approved: true,
  },
    // --- messiahLogos (from messiahLogos.card primaryScriptures, supportingScriptures, bibleFirstConclusion) ---
  {
    id: 'john1_logos_word_deity',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\blogos\b.{0,50}\b(word)\b/i,
      /\bword\b.{0,50}\b(with god|was god|beginning)\b/i,
      /\bwith god\b/i,
      /\bwas god\b/i,
      /\bidentifies logos\b/i,
    ],
    refPatterns: [/\bjohn\s*1:1-14\b/i, /\bjohn\s*1:1\b/i, /\bjohn\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 1:1-14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'messiahLogos.card primaryScriptures + bibleFirstConclusion',
    approved: true,
  },
  {
    id: 'john1_logos_made_flesh',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\b(became|made)\s+flesh\b/i,
      /\bincarnate\b/i,
      /\bword became flesh\b/i,
      /\blogos\b.{0,40}\b(flesh|human|jesus)\b/i,
      /\breveals\b.{0,30}\blogos\b.{0,30}\b(flesh|human)\b/i,
    ],
    refPatterns: [/\bjohn\s*1:14\b/i, /\bjohn\s*1:1\b/i, /\bjohn\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 1:1-14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'messiahLogos.card primaryScriptures',
    approved: true,
  },
  {
    id: 'john1_logos_means_word',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\blogos\b.{0,30}\bmeans\b.{0,30}\bword\b/i,
      /\bterm\b.{0,30}\blogos\b.{0,30}\bmeans\b/i,
      /"logos"\s+means\s+"word"/i,
    ],
    refPatterns: [/\bjohn\s*1:1-14\b/i, /\bjohn\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 1:1-14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'messiahLogos.card primaryScriptures',
    approved: true,
  },
  {
    id: 'gen1_create_by_word',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\b(creat(ed|ive|ion)|creating)\b.{0,40}\b(word|power)\b/i,
      /\bword\b.{0,40}\b(creat|power|paralleling)\b/i,
      /\bparalleling\b.{0,40}\blogos\b/i,
      /\bgod'?s creative power\b/i,
    ],
    refPatterns: [/\bgenesis\s*1:1\b/i, /\bgenesis\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Genesis 1:1'],
    relationship: 'direct',
    confidence: 'high',
    source: 'messiahLogos.card supportingScriptures',
    approved: true,
  },
  {
    id: 'rev19_word_of_god_name',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\bword of god\b/i,
      /\bname\b.{0,30}\bword\b/i,
      /\blinking\b.{0,30}\b(logos|jesus|identity)\b/i,
    ],
    refPatterns: [/\brevelation\s*19:13\b/i, /\brevelation\s*19\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Revelation 19:11-16'],
    relationship: 'direct',
    confidence: 'high',
    source: 'messiahLogos.card supportingScriptures',
    approved: true,
  },
  {
    id: 'col1_image_of_god',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\bimage of god\b/i,
      /\bfirstborn\b.{0,30}\b(all creation|creation)\b/i,
      /\bby him\b.{0,30}\b(all things|created)\b/i,
      /\bpre-?eminenc(e|y)\b/i,
      /\brole in creation\b/i,
      /\bcolossians\b/i,
    ],
    refPatterns: [/\bcol(?:ossians)?\s*1:15/i, /\bcol(?:ossians)?\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Colossians 1:15-17'],
    relationship: 'direct',
    confidence: 'high',
    source: 'messiahLogos.card primaryScriptures',
    approved: true,
  },
  {
    id: 'logos_messiah_ot_witness',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\bmessiah\b.{0,50}\b(old testament|promised)\b/i,
      /\bold testament\b.{0,40}\b(promise|witness|messiah)\b/i,
      /\bpromised messiah\b/i,
      /\bword\b.{0,40}\b(messiah|promised)\b/i,
    ],
    refPatterns: [/\bjohn\s*1:14\b/i, /\bjohn\s*1:1\b/i, /\bjohn\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 1:1-14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'messiahLogos.card bibleFirstConclusion',
    approved: true,
  },
  {
    id: 'rev1_alpha_omega_logos_g2r_batch',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\blogos\b/i,
      /\bword of god\b/i,
      /\balpha\b.{0,30}\bomega\b/i,
      /\brevealed\b.{0,40}\b(word|logos)\b/i,
    ],
    refPatterns: [
      /revelation\s*1:8/i,
      /revelation\s*1\b/i,
    ],
    supportType: 'indirectly_supports',
    scriptures: ['Revelation 1:8', 'Genesis 1:1', 'John 1:1-14', 'Revelation 19:11-16'],
    relationship: 'chain',
    confidence: 'high',
    source: '2J-N/2J-K first batch exp_0005 G2R Logos chain',
    approved: true,
  },
    {
    id: 'john1_who_is_logos_batch3p',
    topic: 'messiah_logos',
    cardId: 'messiahLogos',
    claimPatterns: [
      /\bwho is the logos\b/i,
      /\bwhat is the logos\b/i,
      /\bwho is the word\b.{0,30}\bjohn\b/i,
      /\blogos in john\s*1\b/i,
      /\bidentity of the logos\b/i,
    ],
    refPatterns: [
      /john\s*1:1-14/i,
      /john\s*1\b/i,
    ],
    supportType: 'directly_affirms',
    scriptures: ['John 1:1-14', 'Genesis 1:1', 'Isaiah 9:6', 'Revelation 1:8'],
    relationship: 'chain',
    confidence: 'high',
    source: '2P Messiah Logos Pack rec_0010 Who is the Logos',
    approved: true,
  },
    // --- holiness (from holiness.card + holiness_foundation_continuity refs) ---
  {
    id: 'lev19_be_holy_as_god',
    topic: 'holiness',
    cardId: 'holiness',
    claimPatterns: [
      /\b(be|called to be)\b.{0,20}\bholy\b/i,
      /\bholy\b.{0,30}\b(as|like)\b.{0,20}\b(god|he is|lord)\b/i,
      /\bset apart\b/i,
      /\bgod'?s people\b.{0,30}\bholy\b/i,
      /\bholi(ness)?\b.{0,40}\b(distinct|dedicated|set apart)\b/i,
      /\bbe ye holy\b/i,
    ],
    refPatterns: [/\bleviticus\s*19:2\b/i, /\bleviticus\s*19\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Leviticus 19:2'],
    relationship: 'direct',
    confidence: 'high',
    source: 'holiness.card primaryScriptures',
    approved: true,
  },
  {
    id: '1pet115_be_holy',
    topic: 'holiness',
    cardId: 'holiness',
    claimPatterns: [
      /\b(be|called to be)\b.{0,20}\bholy\b/i,
      /\bholy\b.{0,40}\b(all manner|living|conversation|manner of living|lifestyle|character)\b/i,
      /\bholi(ness)?\b.{0,40}\b(lifestyle|character|reflecting)\b/i,
      /\bbelievers?\b.{0,30}\bholy\b/i,
      /\bfollowing god'?s holiness\b/i,
      /\breiterates\b.{0,30}\b(call|holiness)\b/i,
      /\bpeter\b.{0,40}\bholi(ness)?\b/i,
    ],
    refPatterns: [/\b1\s*peter\s*1:15-16\b/i, /\b1\s*peter\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['1 Peter 1:15-16'],
    relationship: 'direct',
    confidence: 'high',
    source: 'holiness.card primaryScriptures',
    approved: true,
  },
  {
    id: 'lev1144_holy_as_god',
    topic: 'holiness',
    cardId: 'holiness',
    claimPatterns: [
      /\b(holy|sanctif)\b.{0,30}\b(god|lord)\b/i,
      /\bseparate\b.{0,20}\b(holy|yourselves)\b/i,
    ],
    refPatterns: [/\bleviticus\s*11:44-45\b/i, /\bleviticus\s*11:44\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Leviticus 11:44-45'],
    relationship: 'direct',
    confidence: 'high',
    source: 'holiness.card supportingScriptures',
    approved: true,
  },
  {
    id: 'heb1214_pursue_holiness',
    topic: 'holiness',
    cardId: 'holiness',
    claimPatterns: [
      /\bholiness\b.{0,40}\b(without which|see the lord|pursue)\b/i,
      /\bpursue\b.{0,20}\bholiness\b/i,
      /\bwithout holiness\b/i,
    ],
    refPatterns: [/\bhebrews\s*12:14\b/i, /\bhebrews\s*12\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Hebrews 12:14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'holiness.card supportingScriptures',
    approved: true,
  },
  {
    id: 'acts1_ascension_return_promise',
    topic: 'kingdom',
    cardId: 'kingdom',
    claimPatterns: [
      /\bascension\b/i,
      /\bascended\b/i,
      /\breturn\b/i,
      /\bcome again\b/i,
      /\bpromise\b.{0,40}\b(return|future)\b/i,
      /\bwill come\b/i,
      /\bfuture return\b/i,
      /\bjesus\b.{0,40}\b(ascension|ascended|return)\b/i,
      /\bshows\b.{0,30}\b(ascension|return|promise)\b/i,
    ],
    refPatterns: [/\bacts\s*1:9/i, /\bacts\s*1\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Acts 1:9-11'],
    relationship: 'chain',
    confidence: 'medium',
    source: 'deathResurrectionKingdomCatalog.threeHeavens.teachingOrder',
    approved: true,
  },
  // --- deathState (from deathState.card primaryScriptures + supportingScriptures) ---
  {
    id: 'john11_death_as_sleep',
    topic: 'death_state',
    cardId: 'deathState',
    claimPatterns: [
      /\bdeath\b.{0,40}\b(sleep|asleep)\b/i,
      /\bsleep(ing)?\b.{0,40}\b(death|dead|lazarus|resurrection)\b/i,
      /\binactiv(e|ity)\b/i,
      /\bunconscious/i,
      /\btemporary\b.{0,20}\bstate\b/i,
      /\brefers to death as sleep\b/i,
    ],
    refPatterns: [/\bjohn\s*11:11/i, /\bjohn\s*11\b/i],
    supportType: 'directly_affirms',
    scriptures: ['John 11:11-14'],
    relationship: 'direct',
    confidence: 'high',
    source: 'deathState.card primaryScriptures',
    approved: true,
  },
  {
    id: 'eccl9_dead_know_nothing',
    topic: 'death_state',
    cardId: 'deathState',
    claimPatterns: [
      /\bdead\b.{0,30}\b(know not|know nothing)\b/i,
      /\bknow not anything\b/i,
      /\bunconscious/i,
      /\bno (activity|consciousness)\b/i,
    ],
    refPatterns: [/\beccl(?:esiastes)?\s*9:5\b/i, /\beccl(?:esiastes)?\s*9\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Ecclesiastes 9:5'],
    relationship: 'direct',
    confidence: 'high',
    source: 'deathState.card primaryScriptures',
    approved: true,
  },
  {
    id: 'psalm146_breath_departeth',
    topic: 'death_state',
    cardId: 'deathState',
    claimPatterns: [
      /\b(breath|spirit)\b.{0,30}\b(depart|return|earth)\b/i,
      /\bthoughts?\b.{0,20}\bperish\b/i,
      /\breturn(s)?\b.{0,20}\bto the earth\b/i,
    ],
    refPatterns: [/\bpsalm\s*146:4\b/i, /\bpsalm\s*146\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Psalm 146:4'],
    relationship: 'direct',
    confidence: 'high',
    source: 'deathState.card primaryScriptures',
    approved: true,
  },
  {
    id: '1thess4_sleep_until_resurrection',
    topic: 'death_state',
    cardId: 'deathState',
    claimPatterns: [
      /\b(sleep|sleeping)\b.{0,40}\b(resurrection|christ|await)\b/i,
      /\bdead in christ\b/i,
      /\bgriev(e|ing)\b.{0,30}\bhope\b/i,
      /\bawait(ing)?\b.{0,20}\bresurrection\b/i,
      /\bcomfort(s)?\b.{0,30}\b(believers?|dead)\b/i,
      /\bnot to grieve\b/i,
    ],
    refPatterns: [/\b1\s*thess(?:alonians)?\s*4/i],
    supportType: 'directly_affirms',
    scriptures: ['1 Thessalonians 4:13-16'],
    relationship: 'direct',
    confidence: 'high',
    source: 'deathState.card primaryScriptures',
    approved: true,
  },
  {
    id: 'dan12_resurrection_hope',
    topic: 'death_state',
    cardId: 'deathState',
    claimPatterns: [
      /\bresurrection\b/i,
      /\bawaken(ing|ed)?\b.{0,20}\b(dead|dust)\b/i,
      /\bstand\b.{0,20}\b(lot|judgment)\b/i,
    ],
    refPatterns: [/\bdaniel\s*12:2\b/i, /\bdaniel\s*12\b/i],
    supportType: 'directly_affirms',
    scriptures: ['Daniel 12:2'],
    relationship: 'direct',
    confidence: 'high',
    source: 'deathState.card supportingScriptures',
    approved: true,
  },
  {
    id: '1cor15_resurrection_victory',
    topic: 'death_state',
    cardId: 'deathState',
    claimPatterns: [
      /\bresurrection\b/i,
      /\b(corruptible|incorruptible|victory over death)\b/i,
      /\blast trump\b/i,
      /\braised\b.{0,20}\b(imperishable|immortal)\b/i,
    ],
    refPatterns: [/\b1\s*cor(?:inthians)?\s*15/i],
    supportType: 'directly_affirms',
    scriptures: ['1 Corinthians 15:51-55'],
    relationship: 'direct',
    confidence: 'high',
    source: 'deathState.card supportingScriptures',
    approved: true,
  },
  {
    id: 'sunday_replaced_sabbath',
    topic: 'sabbath',
    cardId: 'sabbath',
    claimPatterns: [
      /\bsunday\b.{0,40}\b(replaced|replaces|is the)\b.{0,30}\bsabbath\b/i,
      /\bchristians?\b.{0,30}\bworship\b.{0,20}\bon sunday\b.{0,40}\b(instead of|replacing)\b/i,
    ],
    refPatterns: [/\bsunday\b/i, /\bsabbath\b/i],
    supportType: 'contradicts',
    scriptures: [],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'sabbath.card commonMisreadings',
    approved: true,
  },
  {
    id: 'heaven_at_death_settled',
    topic: 'death_state',
    cardId: 'deathState',
    claimPatterns: [
      /\bwhen (you|we) die\b.{0,50}\b(go|enter|ascend)\b.{0,30}\b(heaven|lord's presence)\b/i,
      /\b(soul|spirit)\b.{0,40}\b(goes?|returns?)\b.{0,30}\bto heaven\b.{0,30}\b(at death|when we die|immediately)\b/i,
    ],
    refPatterns: [/\b2\s*cor(?:inthians)?\s*5:8\b/i],
    supportType: 'contradicts',
    scriptures: ['2 Corinthians 5:8'],
    relationship: 'contradicted',
    confidence: 'high',
    source: 'heavens.card cautionScriptures',
    approved: true,
  },
];

function edgeMatchesClaim(edge, claimText = '', refs = []) {
  const text = String(claimText || '');
  const claimHit = (edge.claimPatterns || []).some((re) => re.test(text));
  if (!claimHit) return false;

  const edgeRefs = edge.refPatterns || [];
  if (!edgeRefs.length) return true;

  if (!refs.length) return false;

  return refs.some((ref) => edgeRefs.some((re) => refMatchesPattern(ref, re)));
}

function classificationForEdge(edge) {
  if (edge.classificationOverride) return edge.classificationOverride;
  if (edge.supportType === 'contradicts') return 'D';
  return SUPPORT_CLASS_BY_TYPE[edge.supportType] || 'C';
}

function buildApprovedSupportGraph(evidencePack = {}) {
  const cards = evidencePack.evidenceCards?.cards || [];
  const cardIds = new Set(cards.map((c) => c.cardId));
  const catalogKeys = new Set(evidencePack.approvedCatalogEvidence?.catalogKeys || []);
  const approvedRefs = collectApprovedReferences(evidencePack.approvedCatalogEvidence || {}, cards);

  let edges = APPROVED_SUPPORT_EDGES.filter((edge) => {
    if (!cardIds.size) return true;
    if (edge.cardId && cardIds.has(edge.cardId)) return true;
    return (edge.scriptures || []).some((s) =>
      approvedRefs.some((r) => refMatchesApproved(s, r) || refMatchesApproved(r, s))
    );
  });

  const catalogEvidence = evidencePack.approvedCatalogEvidence || buildApprovedCatalogEvidence({
    topic: evidencePack.effectiveTopic || evidencePack.topic,
    message: evidencePack.message,
    cardTopics: [...cardIds].map((id) => id),
  });

  for (const chain of catalogEvidence.chains || []) {
    for (const ref of chain.teachingOrder || []) {
      edges.push({
        id: `catalog_chain_${chain.catalogKey}_${ref.replace(/\s+/g, '_')}`,
        topic: chain.catalogKey,
        cardId: null,
        claimPatterns: [],
        refPatterns: [new RegExp(ref.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i')],
        supportType: 'indirectly_supports',
        scriptures: [ref],
        relationship: 'chain',
        confidence: 'medium',
        source: `catalog:${chain.catalogKey}`,
        approved: true,
        chainOnly: true,
      });
    }
  }

  return {
    edges,
    edgeCount: edges.length,
    cardIds: [...cardIds],
    catalogKeys: [...catalogKeys],
    approved: true,
  };
}

function matchSupportGraph(claimText = '', refs = [], supportGraph = {}) {
  const edges = supportGraph.edges || APPROVED_SUPPORT_EDGES;
  const text = String(claimText || '');

  const contradictHits = [];
  const affirmHits = [];

  for (const edge of edges) {
    if (edge.chainOnly) continue;
    if (!edgeMatchesClaim(edge, text, refs)) continue;

    const hit = {
      id: edge.id,
      topic: edge.topic,
      supportType: edge.supportType,
      scriptures: edge.scriptures,
      relationship: edge.relationship || RELATIONSHIP_BY_TYPE[edge.supportType],
      confidence: edge.confidence,
      source: edge.source,
      approved: true,
      classification: classificationForEdge(edge),
    };

    if (edge.supportType === 'contradicts' || edge.classificationOverride === 'D') {
      contradictHits.push(hit);
    } else if (edge.supportType === 'limits_claim') {
      contradictHits.push(hit);
    } else if (edge.supportType === 'directly_affirms' || edge.supportType === 'indirectly_supports') {
      affirmHits.push(hit);
    }
  }

  if (contradictHits.length) {
    return { match: contradictHits[0], matches: contradictHits, outcome: 'contradicted' };
  }
  if (affirmHits.length) {
    return { match: affirmHits[0], matches: affirmHits, outcome: 'affirmed' };
  }

  const chainEdges = edges.filter((e) => e.chainOnly);
  for (const ref of refs) {
    for (const edge of chainEdges) {
      if ((edge.refPatterns || []).some((re) => refMatchesPattern(ref, re))) {
        return {
          match: {
            id: edge.id,
            topic: edge.topic,
            supportType: 'indirectly_supports',
            scriptures: edge.scriptures,
            relationship: 'chain',
            confidence: 'medium',
            source: edge.source,
            approved: true,
            classification: 'B',
          },
          matches: [edge],
          outcome: 'chain',
        };
      }
    }
  }

  return { match: null, matches: [], outcome: 'none' };
}

function getAllApprovedSupportEdges() {
  return [...APPROVED_SUPPORT_EDGES];
}

module.exports = {
  APPROVED_SUPPORT_EDGES,
  SUPPORT_CLASS_BY_TYPE,
  RELATIONSHIP_BY_TYPE,
  buildApprovedSupportGraph,
  matchSupportGraph,
  edgeMatchesClaim,
  classificationForEdge,
  getAllApprovedSupportEdges,
};
