function buildResourceIngestionReview(input = {}) {
  return {
    enabled: true,
    purpose: 'Review scanned or uploaded educational resources before they are added to companion knowledge systems.',
    acceptedResourceTypes: [
      'scanned_documents',
      'pdf_documents',
      'images_of_notes',
      'audio_transcripts',
      'sermon_notes',
      'study_notes',
      'historical_references',
      'lesson_materials',
      'books_or_excerpts_with_rights',
    ],
    intakeWorkflow: [
      'upload_or_scan_resource',
      'ocr_or_transcript_extraction_future',
      'metadata_tagging',
      'scripture_reference_detection',
      'line_upon_line_review',
      'historical_context_review',
      'question_generation_for_reviewer',
      'admin_or_reviewer_review',
      'approval_or_rejection',
      'future_knowledge_ingestion',
    ],
    requiredMetadata: [
      'title',
      'author_or_speaker',
      'summary',
      'language',
      'category',
      'resource_type',
    ],
    optionalMetadata: [
      'scripture_references',
      'historical_period',
      'topic_tags',
      'source_links',
      'usage_notes',
    ],
    companionReviewSupport: {
      enabled: true,
      reviewStyle: 'line_upon_line_precept_upon_precept',
      supportActions: [
        'identify_scripture_references_in_the_resource',
        'suggest_related_scriptures_to_consider',
        'ask_clarifying_questions_when_claims_need_support',
        'compare_historical_claims_to_context_when_available',
        'separate_scripture_from_commentary_or_interpretation',
        'surface_possible_gaps_without_overriding_the_reviewer',
        'recommend_follow_up_review_when_uncertain',
      ],
      examplePrompts: [
        'This lesson mentions a historical event. What source supports that connection?',
        'This point may benefit from another Scripture reference. Would you like to add one?',
        'This interpretation should be clearly labeled as commentary rather than source text.',
        'This historical note appears relevant, but it needs review before being used as teaching support.',
      ],
    },
    aiReviewOutputs: {
      summary: true,
      scriptureReferencesDetected: true,
      relatedReferencesSuggested: true,
      historicalContextQuestions: true,
      possibleConcernFlags: true,
      reviewerQuestions: true,
      approvalRecommendation: 'human_review_required',
    },
    testerAndAdminSignals: [
      'resource_needs_reference_support',
      'resource_has_unclear_historical_claim',
      'resource_has_unclear_source_origin',
      'resource_has_possible_commentary_confusion',
      'resource_ready_for_human_review',
      'resource_rejected_or_disabled',
    ],
    moderationRules: [
      'Track source origin.',
      'Allow removal of disputed materials.',
      'Keep review history.',
      'Do not auto-publish unreviewed materials.',
      'Do not treat AI review as final authority.',
      'Require human approval before knowledge ingestion.',
      'Respect copyright and usage rights.',
    ],
    futureIngestion: {
      ragReady: true,
      ocrReady: true,
      transcriptReady: true,
      sourceGraphReady: true,
      adminDashboardReady: true,
      testingFeedbackReady: true,
    },
  };
}

module.exports = { buildResourceIngestionReview };
