function buildResourceIngestionReview(input = {}) {
  return {
    enabled: true,
    purpose: 'Review scanned or uploaded educational resources before they are added to companion knowledge systems.',
    acceptedResourceTypes: [
      'scanned_documents',
      'pdf_documents',
      'images_of_notes',
      'audio_transcripts',
      'sermon_notes',
      'study_notes',
      'historical_references',
      'lesson_materials',
      'books_or_excerpts_with_rights',
    ],
    intakeWorkflow: [
      'upload_or_scan_resource',
      'ocr_or_transcript_extraction_future',
      'metadata_tagging',
      'scripture_reference_detection',
      'line_upon_line_review',
      'historical_context_review',
      'question_generation_for_reviewer',
      'alignment_severity_scoring',
      'admin_or_reviewer_review',
      'approval_or_rejection',
      'future_knowledge_ingestion',
    ],
    requiredMetadata: [
      'title',
      'author_or_speaker',
      'summary',
      'language',
      'category',
      'resource_type',
    ],
    optionalMetadata: [
      'scripture_references',
      'historical_period',
      'topic_tags',
      'source_links',
      'usage_notes',
    ],
    companionReviewSupport: {
      enabled: true,
      reviewStyle: 'line_upon_line_precept_upon_precept',
      supportActions: [
        'identify_scripture_references_in_the_resource',
        'suggest_related_scriptures_to_consider',
        'ask_clarifying_questions_when_claims_need_support',
        'compare_historical_claims_to_context_when_available',
        'separate_scripture_from_commentary_or_interpretation',
        'surface_possible_gaps_without_overriding_the_reviewer',
        'recommend_follow_up_review_when_uncertain',
      ],
      examplePrompts: [
        'This lesson mentions a historical event. What source supports that connection?',
        'This point may benefit from another Scripture reference. Would you like to add one?',
        'This interpretation should be clearly labeled as commentary rather than source text.',
        'This historical note appears relevant, but it needs review before being used as teaching support.',
      ],
    },
    alignmentSeverity: {
      addable: {
        level: 1,
        label: 'Addable supporting precept',
        meaning: 'The reviewer supplied a reference or line of thought that appears to support the lesson and can be considered for addition after review.',
        action: 'suggest_addition_for_reviewer_confirmation',
      },
      needsSupport: {
        level: 2,
        label: 'Needs more support',
        meaning: 'The idea may fit, but needs clearer references, stronger source context, or reviewer explanation before use.',
        action: 'ask_reviewer_clarifying_questions_and_send_to_admin_queue',
      },
      uncertainHistory: {
        level: 3,
        label: 'Historical/context uncertainty',
        meaning: 'The historical claim may be useful, but source origin, timing, or connection needs human review.',
        action: 'flag_for_history_context_review',
      },
      conflictOrUnsupported: {
        level: 4,
        label: 'Conflict or unsupported claim',
        meaning: 'The reference, interpretation, or history does not clearly align with the supplied source material or needs correction.',
        action: 'do_not_ingest_send_to_admin_with_reasoning',
      },
      highRiskTeaching: {
        level: 5,
        label: 'High review priority',
        meaning: 'The material could significantly affect teaching, doctrine, safety, or user trust and must be reviewed before use.',
        action: 'lock_from_ingestion_until_human_approval',
      },
    },
    adminReviewPacket: {
      include: [
        'resource_summary',
        'detected_references',
        'suggested_related_references',
        'reviewer_claim',
        'ai_reasoning_summary',
        'historical_context_questions',
        'severity_level',
        'recommended_action',
        'human_review_required',
      ],
      purpose: 'Help admin quickly understand what was added, what was uncertain, what may not align, and why the item was flagged.',
    },
    aiReviewOutputs: {
      summary: true,
      scriptureReferencesDetected: true,
      relatedReferencesSuggested: true,
      historicalContextQuestions: true,
      possibleConcernFlags: true,
      reviewerQuestions: true,
      approvalRecommendation: 'human_review_required',
      severityScoring: true,
    },
    testerAndAdminSignals: [
      'resource_needs_reference_support',
      'resource_has_unclear_historical_claim',
      'resource_has_unclear_source_origin',
      'resource_has_possible_commentary_confusion',
      'resource_ready_for_human_review',
      'resource_rejected_or_disabled',
      'resource_has_addable_precept',
      'resource_locked_pending_review',
    ],
    moderationRules: [
      'Track source origin.',
      'Allow removal of disputed materials.',
      'Keep review history.',
      'Do not auto-publish unreviewed materials.',
      'Do not treat AI review as final authority.',
      'Require human approval before knowledge ingestion.',
      'Respect copyright and usage rights.',
    ],
    futureIngestion: {
      ragReady: true,
      ocrReady: true,
      transcriptReady: true,
      sourceGraphReady: true,
      adminDashboardReady: true,
      testingFeedbackReady: true,
    },
  };
}

module.exports = { buildResourceIngestionReview };
